### ISSUE TITLE
backend route status not updating correctly

### ISSUE THREAD

**Issue by marcellosachs** [marcellosachs/count#1]
1) submit a survey on a route
2) the route is still marked as not_started in the graphql

3) submit a survey on a different route within the same team
4) expectation: the previous route is now marked as complete, but it is still marked as not_started

**Comment by echeon** [comment]
1) If there is no previous survey submitted for the route, it will mark the route as 'in_progress'.

2) If the previous route has different route, then it will mark the previous route as 'complete' and the new route as 'in_progress'
